import { FAMILIAS } from "./fonts";
import type { Marca } from "./types";

/**
 * Las trece marcas de carros y concesionarios de `apps/clients/`.
 *
 * Todo sale de sus webs, no se inventa: la paleta es la de su `globals.css`
 * (oklch pasado a hex), la tipografía de titulares es la de su `app/layout.js`
 * y el tagline, la ciudad y los seguidores son los de su `config.js`. El
 * dominio es el alias de producción de su demo en Vercel. Lo único propio del video es el diferencial de la escena 4, que
 * resume en tres líneas lo que su web ya cuenta en varias secciones.
 *
 * El orden es el de la barra lateral del estudio.
 */
export const MARCAS: Marca[] = [
  {
    id: "aprovechalo",
    cliente: "aprovechalo-ve",
    nombre: "Aprovéchalo",
    tagline: "Cumpliendo sueños",
    ciudad: "Venezuela",
    dominio: "aprovechalo-ve.vercel.app",
    seguidores: "42,7 K",
    claro: true,
    colores: {
      fondo: "#FFFFFF",
      superficie: "#F4F5F6",
      linea: "#E6E8EA",
      tinta: "#14191E",
      humo: "#83868A",
      primario: "#D42325",
      sobrePrimario: "#FCFCFC",
      acento: "#13161A",
    },
    display: { family: FAMILIAS.sora, weight: 700, tracking: "-0.035em" },
    logo: { kind: "imagen", src: "concesionarios/aprovechalo/logo.jpg", fondo: "#000000" },
    diferencial: {
      kicker: "Lo que se mueve aquí",
      lineas: ["Carros.", "Camionetas.", "Motos."],
      nota: "Verificados, con precio en dólares y atención directa por WhatsApp.",
    },
  },
  {
    id: "cittacars",
    cliente: "cittacars",
    nombre: "Citta Cars",
    tagline: "Somos tu concesionario de confianza",
    ciudad: "Venezuela",
    dominio: "cittacars.vercel.app",
    seguidores: "5.427",
    colores: {
      fondo: "#0B0B0B",
      superficie: "#151515",
      linea: "#242424",
      tinta: "#F5F5F5",
      humo: "#8F8F8F",
      primario: "#D72828",
      sobrePrimario: "#FCFCFC",
      acento: "#008548",
    },
    display: { family: FAMILIAS.sora, weight: 700, tracking: "-0.035em" },
    logo: { kind: "imagen", src: "concesionarios/cittacars/logo.jpg", fondo: "#000000" },
    franja: ["#008548", "#F5F5F5", "#D72828"],
    diferencial: {
      kicker: "Showroom + taller",
      lineas: ["Accesorios 4x4.", "Detailing.", "Listo para rodar."],
      nota: "La camioneta sale del showroom como tú la quieres, sin llevarla a otro sitio.",
    },
  },
  {
    id: "ventanacional",
    cliente: "ventananacional",
    nombre: "Venta Nacional",
    tagline: "Concesionaria de automóviles",
    ciudad: "Caracas · Barcelona",
    dominio: "ventananacional.vercel.app",
    seguidores: "160 mil",
    colores: {
      fondo: "#0E1114",
      superficie: "#171A1E",
      linea: "#23272C",
      tinta: "#F0F2F4",
      humo: "#B4B7BD",
      primario: "#EDB91E",
      sobrePrimario: "#191309",
      acento: "#2D5ED4",
    },
    display: { family: FAMILIAS.sairaBold, weight: 700, tracking: "-0.02em" },
    logo: { kind: "imagen", src: "concesionarios/ventanacional/logo.jpg", fondo: "#E6E6E6" },
    franja: ["#EDB91E", "#2D5ED4", "#E23532"],
    diferencial: {
      kicker: "Dos salas",
      lineas: ["Compramos.", "Vendemos.", "Consignamos."],
      nota: "En El Rosal (Caracas) y en Barcelona (Anzoátegui). También importamos.",
    },
  },
  {
    id: "hb-inversiones",
    cliente: "hb-inversiones",
    nombre: "HB Inversiones",
    tagline: "Importamos y vendemos el auto de tus sueños",
    ciudad: "Barquisimeto",
    dominio: "hb-inversiones.vercel.app",
    seguidores: "10,2 K",
    colores: {
      fondo: "#070707",
      superficie: "#101010",
      linea: "#1F1F1F",
      tinta: "#F5F5F5",
      humo: "#868686",
      primario: "#D60016",
      sobrePrimario: "#FCFCFC",
      acento: "#9B0000",
    },
    display: { family: FAMILIAS.barlow, weight: 800, italic: true, tracking: "-0.005em" },
    logo: { kind: "imagen", src: "concesionarios/hb-inversiones/logo.jpg", fondo: "#F2F2F2" },
    diferencial: {
      kicker: "Barquisimeto, Lara",
      lineas: ["0 km financiados.", "Usados verificados."],
      nota: "Av. Venezuela con calles 11 y 12. Cada unidad con su ficha y su precio a la vista.",
    },
  },
  {
    id: "dealernauta",
    cliente: "dealernautacars",
    nombre: "DealerNauta Cars",
    nombreCorto: "DealerNauta",
    tagline: "Tu vehículo soñado convertido en realidad",
    ciudad: "Caracas",
    dominio: "dealernautacars.vercel.app",
    seguidores: "68,4 K",
    colores: {
      fondo: "#060606",
      superficie: "#0F0F0F",
      linea: "#1E1E1E",
      tinta: "#F5F5F5",
      humo: "#868686",
      primario: "#EA702C",
      sobrePrimario: "#130502",
      acento: "#FAAA49",
    },
    display: { family: FAMILIAS.barlow, weight: 800, italic: true, tracking: "-0.005em" },
    logo: { kind: "imagen", src: "concesionarios/dealernauta/logo.jpg", fondo: "#000000" },
    diferencial: {
      kicker: "Dos negocios, una marca",
      lineas: ["Vehículos.", "Camiones."],
      nota: "Carros en Los Chaguaramos y camiones en San Antonio de los Altos, cada uno con su sección.",
    },
  },
  {
    id: "veloce",
    cliente: "veloce-autos",
    nombre: "Veloce Autos",
    tagline: "Importación directa",
    ciudad: "Caracas",
    dominio: "veloce-autos-nine.vercel.app",
    seguidores: "222 K",
    colores: {
      fondo: "#060608",
      superficie: "#0F0F11",
      linea: "#1C1D1F",
      tinta: "#F5F5F5",
      humo: "#84868A",
      primario: "#F5F5F5",
      sobrePrimario: "#060608",
      acento: "#A1A5AC",
    },
    display: { family: FAMILIAS.sairaSemi, weight: 600, tracking: "0.02em" },
    logo: { kind: "veloce" },
    diferencial: {
      kicker: "Importación directa",
      lineas: ["Dubái.", "Europa.", "China.", "EE. UU."],
      nota: "Autos premium, nuevos y usados. Showroom en La Florida y sede en Chacao.",
    },
  },
  {
    id: "lm2006",
    cliente: "im2006",
    nombre: "LM 2006",
    tagline: "Concesionario de vehículos y camiones",
    ciudad: "Caracas",
    dominio: "lm2006.vercel.app",
    seguidores: "9.179",
    colores: {
      fondo: "#0B0D11",
      superficie: "#15181D",
      linea: "#22272D",
      tinta: "#F5F5F5",
      humo: "#83868B",
      primario: "#0059FF",
      sobrePrimario: "#FCFCFC",
      acento: "#FF1F20",
    },
    display: { family: FAMILIAS.barlow, weight: 800, italic: true, tracking: "-0.005em" },
    logo: { kind: "imagen", src: "concesionarios/lm2006/logo.jpg", fondo: "#16181C" },
    franja: ["#FF1F20", "#0059FF"],
    diferencial: {
      kicker: "Los Chaguaramos, Caracas",
      lineas: ["Compra.", "Venta.", "Consignación."],
      nota: "0 km con su ficha completa y camiones Sinotruk, con el precio a la vista.",
    },
  },
  {
    id: "susu-cars",
    cliente: "susu-cars",
    nombre: "SUSU CARS",
    tagline: "Vende tu vehículo en tiempo récord y con seguridad",
    ciudad: "Caracas",
    dominio: "susu-cars.vercel.app",
    colores: {
      fondo: "#060605",
      superficie: "#0F0E0C",
      linea: "#1E1D1A",
      tinta: "#F3F2EF",
      humo: "#878683",
      primario: "#C9A24A",
      sobrePrimario: "#0A0907",
      acento: "#E7D7A7",
    },
    display: { family: FAMILIAS.cinzel, weight: 700, tracking: "0.015em" },
    logo: { kind: "imagen", src: "concesionarios/susu-cars/logo.jpg", fondo: "#101014" },
    problema: {
      a: "Quien quiere vender su carro no sabe en quién confiar.",
      b: "¿Dónde ve cómo trabajas?",
    },
    diferencial: {
      kicker: "Consignación",
      lineas: ["Tú lo traes.", "Nosotros lo vendemos."],
      nota: "Lo fotografiamos, lo publicamos y sigue siendo tuyo hasta que se venda. Av. Casanova.",
    },
  },
  {
    id: "dss-import",
    cliente: "dss-import",
    nombre: "DSS Import & Export",
    nombreCorto: "DSS",
    tagline: "Confianza y seguridad en movimiento",
    ciudad: "Maracay",
    dominio: "dss-import.vercel.app",
    seguidores: "43,2 K",
    colores: {
      fondo: "#060606",
      superficie: "#0F0F0F",
      linea: "#1E1E1E",
      tinta: "#F5F5F5",
      humo: "#868686",
      primario: "#DBA840",
      sobrePrimario: "#100A03",
      acento: "#EDD692",
    },
    display: { family: FAMILIAS.barlow, weight: 800, italic: true, tracking: "-0.005em" },
    logo: { kind: "imagen", src: "concesionarios/dss-import/logo.jpg", fondo: "#DBA840" },
    llamadaPrecio: "La cuota por delante, antes que el precio",
    diferencial: {
      kicker: "Planes de crédito",
      lineas: ["Cuotas desde $75", "a la semana."],
      nota: "Vehículos y motos financiados hasta 2 años. Maracay, Aragua.",
    },
  },
  {
    id: "kingscars",
    cliente: "kingscars",
    nombre: "Kings Cars",
    tagline: "¿Comprar o vender tu vehículo? Para eso estamos",
    ciudad: "C.C.C.T., Caracas",
    dominio: "kingscars.vercel.app",
    seguidores: "6.567",
    colores: {
      fondo: "#0B0B0B",
      superficie: "#151515",
      linea: "#242424",
      tinta: "#F8F8F8",
      humo: "#898989",
      primario: "#D92225",
      sobrePrimario: "#FCFCFC",
      acento: "#F0584B",
    },
    display: { family: FAMILIAS.chakra, weight: 700, tracking: "-0.01em" },
    logo: { kind: "imagen", src: "concesionarios/kingscars/logo.jpg", fondo: "#2A2A2A" },
    diferencial: {
      kicker: "Publica tu vehículo",
      lineas: ["Gratis."],
      nota: "Avalúo, fotos, promoción y seguimiento de venta. En el C.C.C.T., previa cita.",
    },
  },
  {
    id: "top-miami-cars",
    cliente: "top-miami-cars",
    nombre: "Top Miami Cars",
    tagline: "Usados top, listos para rodar",
    ciudad: "Caracas",
    dominio: "top-miami-cars.vercel.app",
    claro: true,
    colores: {
      fondo: "#FFFFFF",
      superficie: "#F3F5F7",
      linea: "#E1E5E9",
      tinta: "#091235",
      humo: "#677073",
      primario: "#001478",
      sobrePrimario: "#FFFFFF",
      acento: "#1B3CB8",
    },
    display: { family: FAMILIAS.russo, weight: 400, tracking: "0.005em" },
    logo: { kind: "imagen", src: "concesionarios/top-miami-cars/logo.webp", fondo: "#FFFFFF" },
    problema: {
      a: "Hoy cada unidad se explica por WhatsApp, una por una.",
      b: "¿Dónde ven tu inventario completo?",
    },
    diferencial: {
      kicker: "Av. Los Mangos, Caracas",
      lineas: ["Camionetas.", "Sedanes.", "Pick-ups."],
      nota: "Usados revisados, cada uno con su ficha completa y su precio a la vista.",
    },
  },
  {
    id: "coronadocarss",
    cliente: "coronadocars",
    nombre: "Coronado Carss",
    tagline: "Servimos con Excelencia",
    ciudad: "Valencia",
    dominio: "coronado-carss.vercel.app",
    seguidores: "71,8 mil",
    colores: {
      fondo: "#05112D",
      superficie: "#08193E",
      linea: "#122857",
      tinta: "#F6F8FD",
      humo: "#8993A5",
      primario: "#E2F734",
      sobrePrimario: "#04153C",
      acento: "#1950CC",
    },
    display: { family: FAMILIAS.exo, weight: 800, italic: true, tracking: "-0.01em" },
    logo: { kind: "coronado" },
    diferencial: {
      kicker: "Valencia, Carabobo",
      lineas: ["Compra.", "Venta.", "Consignación."],
      nota: "Del Grupo Autos del Centro. Usados y 0 km con año, kilometraje y transmisión a la vista.",
    },
  },
  {
    id: "lone-star",
    cliente: "lone-star",
    nombre: "Lone Star All In Autos",
    nombreCorto: "Lone Star",
    tagline: "Tu vehículo, nuestro compromiso",
    ciudad: "Texas, USA",
    dominio: "lone-star-all-in-autos.vercel.app",
    colores: {
      fondo: "#060505",
      superficie: "#100C0C",
      linea: "#1E1919",
      tinta: "#F4F5F7",
      humo: "#868686",
      primario: "#E11B22",
      sobrePrimario: "#FCFCFC",
      acento: "#1A3363",
    },
    display: { family: FAMILIAS.barlow, weight: 800, italic: true, tracking: "-0.005em" },
    logo: { kind: "imagen", src: "concesionarios/lone-star/logo.jpg", fondo: "#000000" },
    problema: {
      a: "Tus lotes de subasta vencen antes de que alguien los vea.",
      b: "¿Dónde los ven todos juntos?",
    },
    llamadaPrecio: "Cada lote con millas y daño a la vista",
    diferencial: {
      kicker: "De la subasta a tu puerta",
      lineas: ["Compramos.", "Reparamos.", "Exportamos."],
      nota: "Subastas de EE. UU. → taller en Texas → Venezuela, Panamá, Colombia y toda Latinoamérica.",
    },
  },
];
