-- =============================================================================
-- Semilla del LIBRO DE ENTRENAMIENTO (public.exercise_library)
-- 302 ejercicios con animación (3 fotogramas) de @bryllim/workout-guide.
--
-- GENERADO AUTOMÁTICAMENTE por scripts/build-exercise-catalog.mjs — no lo edites
-- a mano: vuelve a ejecutar el script.
--
-- Ejecútalo DESPUÉS de migrations/20260911100000_esquema_completo.sql
-- Es idempotente: puedes volver a correrlo (on conflict do update).
--
-- Ilustraciones: Bryl Lim (CC BY-SA 4.0), derivadas de Everkinetic (CC BY-SA 4.0).
-- =============================================================================

insert into public.exercise_library
  (slug, name, name_en, equipment, primary_muscle, secondary_muscles,
   exercise_type, is_stretch, category, animation_slug)
values
  ('decline-sit-up', 'Abdominales en banco declinado', 'Decline Sit-Up', 'Banco', 'Core', array['Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'decline-sit-up'),
  ('banded-standing-hip-abduction', 'Abducción de cadera de pie con banda', 'Banded Standing Hip Abduction', 'Banda elástica', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-standing-hip-abduction'),
  ('cable-standing-hip-abduction', 'Abducción de cadera de pie en polea', 'Cable Standing Hip Abduction', 'Polea', 'Glúteos', array['Core']::text[], 'weight_reps', false, 'fuerza', 'cable-standing-hip-abduction'),
  ('banded-seated-hip-abduction', 'Abducción de cadera sentado con banda', 'Banded Seated Hip Abduction', 'Banda elástica', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-seated-hip-abduction'),
  ('side-lying-hip-abduction', 'Abducción de cadera tumbado de lado', 'Side-Lying Hip Abduction', 'Peso corporal', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'side-lying-hip-abduction'),
  ('fire-hydrant', 'Abducción en cuadrupedia', 'Fire Hydrant', 'Peso corporal', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'fire-hydrant'),
  ('banded-fire-hydrant', 'Abducción en cuadrupedia con banda', 'Banded Fire Hydrant', 'Banda elástica', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-fire-hydrant'),
  ('hip-abduction-machine', 'Abductores en máquina', 'Hip Abduction Machine', 'Máquina', 'Glúteos', array['Core']::text[], 'weight_reps', false, 'fuerza', 'hip-abduction-machine'),
  ('cable-standing-hip-adduction', 'Aducción de cadera de pie en polea', 'Cable Standing Hip Adduction', 'Polea', 'Aductores', array['Core', 'Glúteos']::text[], 'weight_reps', false, 'fuerza', 'cable-standing-hip-adduction'),
  ('hip-adduction-machine', 'Aductores en máquina', 'Hip Adduction Machine', 'Máquina', 'Aductores', array['Core']::text[], 'weight_reps', false, 'fuerza', 'hip-adduction-machine'),
  ('clamshell', 'Almeja (clamshell)', 'Clamshell', 'Peso corporal', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'clamshell'),
  ('banded-clamshell', 'Almeja con banda', 'Banded Clamshell', 'Banda elástica', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-clamshell'),
  ('reverse-snow-angel', 'Ángel invertido', 'Reverse Snow Angel', 'Peso corporal', 'Espalda alta', array['Deltoides posterior', 'Zona lumbar', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'reverse-snow-angel'),
  ('band-pull-apart', 'Aperturas con banda', 'Band Pull-Apart', 'Banda elástica', 'Espalda alta', array['Deltoides posterior', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'band-pull-apart'),
  ('dumbbell-fly', 'Aperturas con mancuernas', 'Dumbbell Fly', 'Mancuernas', 'Pecho', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-fly'),
  ('cable-fly', 'Aperturas en polea', 'Cable Fly', 'Polea', 'Pecho', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'cable-fly'),
  ('incline-cable-fly', 'Aperturas inclinadas en polea', 'Incline Cable Fly', 'Polea', 'Pecho', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'incline-cable-fly'),
  ('rear-delt-fly', 'Aperturas posteriores', 'Rear Delt Fly', 'Mancuernas', 'Deltoides posterior', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'rear-delt-fly'),
  ('cable-rear-delt-fly', 'Aperturas posteriores en polea', 'Cable Rear Delt Fly', 'Polea', 'Deltoides posterior', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'cable-rear-delt-fly'),
  ('assault-bike', 'Assault bike', 'Assault Bike', 'Cardio', 'Piernas', array['Cardio', 'Hombros']::text[], 'distance_duration', false, 'cardio', 'assault-bike'),
  ('step-down', 'Bajada controlada del cajón', 'Step-Down', 'Cajón', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Gemelos']::text[], 'bodyweight_reps', false, 'fuerza', 'step-down'),
  ('leg-swings-stretch', 'Balanceo de piernas', 'Leg Swings', 'Peso corporal', 'Movilidad', array['Cadera', 'Isquiotibiales', 'Cuádriceps']::text[], 'duration', true, 'movilidad', 'leg-swings-stretch'),
  ('cycling', 'Bicicleta', 'Cycling', 'Cardio', 'Piernas', array['Cardio']::text[], 'distance_duration', false, 'cardio', 'cycling'),
  ('bird-dog', 'Bird dog', 'Bird Dog', 'Peso corporal', 'Core', array['Glúteos', 'Hombros']::text[], 'bodyweight_reps', false, 'core', 'bird-dog'),
  ('good-morning', 'Buenos días (good morning)', 'Good Morning', 'Barra', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'good-morning'),
  ('burpee', 'Burpee', 'Burpee', 'Peso corporal', 'Piernas', array['Pecho', 'Hombros', 'Core', 'Cardio']::text[], 'bodyweight_reps', false, 'fuerza', 'burpee'),
  ('walking', 'Caminar', 'Walking', 'Cardio', 'Piernas', array['Cardio']::text[], 'distance_duration', false, 'cardio', 'walking'),
  ('lying-hamstring-walkout', 'Caminata de isquios tumbado', 'Lying Hamstring Walkout', 'Peso corporal', 'Isquiotibiales', array['Glúteos', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'lying-hamstring-walkout'),
  ('treadmill-incline-walk', 'Caminata inclinada en cinta', 'Treadmill Incline Walk', 'Cardio', 'Piernas', array['Glúteos', 'Cardio']::text[], 'distance_duration', false, 'cardio', 'treadmill-incline-walk'),
  ('banded-lateral-walk', 'Caminata lateral con banda', 'Banded Lateral Walk', 'Banda elástica', 'Glúteos', array['Cuádriceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-lateral-walk'),
  ('arm-circles', 'Círculos de brazos', 'Arm Circles', 'Peso corporal', 'Hombros', array['Pecho', 'Espalda alta', 'Movilidad']::text[], 'duration', true, 'movilidad', 'arm-circles'),
  ('active-hang', 'Colgarse activo', 'Active Hang', 'Barra de dominadas', 'Dorsales', array['Espalda alta', 'Antebrazos', 'Core']::text[], 'duration', false, 'fuerza', 'active-hang'),
  ('dead-hang', 'Colgarse pasivo', 'Dead Hang', 'Barra de dominadas', 'Antebrazos', array['Dorsales', 'Hombros', 'Core']::text[], 'duration', false, 'fuerza', 'dead-hang'),
  ('pec-deck', 'Contractor de pecho (peck deck)', 'Pec Deck', 'Máquina', 'Pecho', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'pec-deck'),
  ('reverse-pec-deck', 'Contractor inverso', 'Reverse Pec Deck', 'Máquina', 'Deltoides posterior', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'reverse-pec-deck'),
  ('running', 'Correr', 'Running', 'Cardio', 'Piernas', array['Cardio']::text[], 'distance_duration', false, 'cardio', 'running'),
  ('crunch', 'Crunch abdominal', 'Crunch', 'Peso corporal', 'Core', '{}'::text[], 'bodyweight_reps', false, 'core', 'crunch'),
  ('bicycle-crunch', 'Crunch bicicleta', 'Bicycle Crunch', 'Peso corporal', 'Core', array['Piernas']::text[], 'bodyweight_reps', false, 'core', 'bicycle-crunch'),
  ('weighted-crunch', 'Crunch con peso', 'Weighted Crunch', 'Disco', 'Core', '{}'::text[], 'weight_reps', false, 'core', 'weighted-crunch'),
  ('cable-crunch', 'Crunch en polea', 'Cable Crunch', 'Polea', 'Core', '{}'::text[], 'weight_reps', false, 'core', 'cable-crunch'),
  ('reverse-crunch', 'Crunch inverso', 'Reverse Crunch', 'Peso corporal', 'Core', '{}'::text[], 'bodyweight_reps', false, 'core', 'reverse-crunch'),
  ('battle-ropes', 'Cuerdas de batalla', 'Battle Ropes', 'Cardio', 'Hombros', array['Core', 'Cardio']::text[], 'duration', false, 'cardio', 'battle-ropes'),
  ('ez-bar-curl', 'Curl con barra Z', 'EZ-Bar Curl', 'Barra', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'ez-bar-curl'),
  ('concentration-curl', 'Curl concentrado', 'Concentration Curl', 'Mancuernas', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'concentration-curl'),
  ('bicep-curl', 'Curl de bíceps', 'Bicep Curl', 'Mancuernas', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'bicep-curl'),
  ('wrist-curl', 'Curl de muñeca', 'Wrist Curl', 'Barra', 'Antebrazos', '{}'::text[], 'weight_reps', false, 'fuerza', 'wrist-curl'),
  ('drag-curl', 'Curl drag', 'Drag Curl', 'Barra', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'drag-curl'),
  ('preacher-curl', 'Curl en banco Scott', 'Preacher Curl', 'Máquina', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'preacher-curl'),
  ('cable-curl', 'Curl en polea', 'Cable Curl', 'Polea', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'cable-curl'),
  ('leg-curl', 'Curl femoral', 'Leg Curl', 'Máquina', 'Isquiotibiales', array['Gemelos']::text[], 'weight_reps', false, 'fuerza', 'leg-curl'),
  ('stability-ball-hamstring-curl', 'Curl femoral con fitball', 'Stability Ball Hamstring Curl', 'Fitball', 'Isquiotibiales', array['Glúteos', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'stability-ball-hamstring-curl'),
  ('towel-hamstring-curl', 'Curl femoral con toalla', 'Towel Hamstring Curl', 'Toalla', 'Isquiotibiales', array['Glúteos', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'towel-hamstring-curl'),
  ('seated-leg-curl', 'Curl femoral sentado', 'Seated Leg Curl', 'Máquina', 'Isquiotibiales', array['Gemelos']::text[], 'weight_reps', false, 'fuerza', 'seated-leg-curl'),
  ('lying-leg-curl', 'Curl femoral tumbado', 'Lying Leg Curl', 'Máquina', 'Isquiotibiales', array['Gemelos']::text[], 'weight_reps', false, 'fuerza', 'lying-leg-curl'),
  ('incline-dumbbell-curl', 'Curl inclinado con mancuernas', 'Incline Dumbbell Curl', 'Mancuernas', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'incline-dumbbell-curl'),
  ('reverse-curl', 'Curl inverso', 'Reverse Curl', 'Barra', 'Antebrazos', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'reverse-curl'),
  ('hammer-curl', 'Curl martillo', 'Hammer Curl', 'Mancuernas', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'hammer-curl'),
  ('rope-hammer-curl', 'Curl martillo con cuerda', 'Rope Hammer Curl', 'Polea', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'rope-hammer-curl'),
  ('nordic-hamstring-curl', 'Curl nórdico', 'Nordic Hamstring Curl', 'Peso corporal', 'Isquiotibiales', array['Glúteos', 'Gemelos']::text[], 'bodyweight_reps', false, 'fuerza', 'nordic-hamstring-curl'),
  ('spider-curl', 'Curl spider', 'Spider Curl', 'Mancuernas', 'Bíceps', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'spider-curl'),
  ('dead-bug', 'Dead bug', 'Dead Bug', 'Peso corporal', 'Core', array['Piernas']::text[], 'bodyweight_reps', false, 'core', 'dead-bug'),
  ('banded-dead-bug', 'Dead bug con banda', 'Banded Dead Bug', 'Banda elástica', 'Core', array['Glúteos', 'Hombros']::text[], 'bodyweight_reps', false, 'core', 'banded-dead-bug'),
  ('lateral-shuffle', 'Desplazamiento lateral', 'Lateral Shuffle', 'Peso corporal', 'Piernas', array['Glúteos', 'Gemelos', 'Cardio']::text[], 'duration', false, 'fuerza', 'lateral-shuffle'),
  ('commando-pull-up', 'Dominada comando', 'Commando Pull-up', 'Barra de dominadas', 'Dorsales', array['Bíceps', 'Espalda alta', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'commando-pull-up'),
  ('towel-pull-up', 'Dominada con toalla', 'Towel Pull-up', 'Toalla', 'Dorsales', array['Bíceps', 'Antebrazos', 'Espalda alta']::text[], 'bodyweight_reps', false, 'fuerza', 'towel-pull-up'),
  ('l-sit-pull-up', 'Dominada en L', 'L-Sit Pull-up', 'Barra de dominadas', 'Dorsales', array['Bíceps', 'Core', 'Antebrazos']::text[], 'bodyweight_reps', false, 'fuerza', 'l-sit-pull-up'),
  ('scapular-pull-up', 'Dominada escapular', 'Scapular Pull-up', 'Barra de dominadas', 'Dorsales', array['Espalda alta', 'Antebrazos', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'scapular-pull-up'),
  ('negative-pull-up', 'Dominada negativa', 'Negative Pull-up', 'Barra de dominadas', 'Dorsales', array['Bíceps', 'Espalda alta', 'Antebrazos']::text[], 'bodyweight_reps', false, 'fuerza', 'negative-pull-up'),
  ('pull-up', 'Dominadas', 'Pull-up', 'Peso corporal', 'Dorsales', array['Bíceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'pull-up'),
  ('neutral-grip-pull-up', 'Dominadas agarre neutro', 'Neutral-Grip Pull-up', 'Peso corporal', 'Dorsales', array['Bíceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'neutral-grip-pull-up'),
  ('assisted-pull-up', 'Dominadas asistidas', 'Assisted Pull-up', 'Máquina', 'Dorsales', array['Bíceps']::text[], 'assisted_bodyweight', false, 'fuerza', 'assisted-pull-up'),
  ('weighted-pull-up', 'Dominadas con lastre', 'Weighted Pull-up', 'Peso corporal', 'Dorsales', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'weighted-pull-up'),
  ('chin-up', 'Dominadas supinas', 'Chin-up', 'Peso corporal', 'Bíceps', array['Dorsales']::text[], 'bodyweight_reps', false, 'fuerza', 'chin-up'),
  ('assisted-chin-up', 'Dominadas supinas asistidas', 'Assisted Chin-up', 'Máquina', 'Bíceps', array['Dorsales']::text[], 'assisted_bodyweight', false, 'fuerza', 'assisted-chin-up'),
  ('weighted-chin-up', 'Dominadas supinas con lastre', 'Weighted Chin-up', 'Peso corporal', 'Bíceps', array['Dorsales']::text[], 'weight_reps', false, 'fuerza', 'weighted-chin-up'),
  ('dragon-flag', 'Dragon flag', 'Dragon Flag', 'Peso corporal', 'Core', array['Dorsales', 'Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'dragon-flag'),
  ('worlds-greatest-stretch', 'El mejor estiramiento del mundo', 'World''s Greatest Stretch', 'Peso corporal', 'Movilidad', array['Cadera', 'Isquiotibiales', 'Espalda alta']::text[], 'duration', true, 'movilidad', 'worlds-greatest-stretch'),
  ('calf-raise', 'Elevación de gemelos', 'Calf Raise', 'Peso corporal', 'Gemelos', '{}'::text[], 'bodyweight_reps', false, 'fuerza', 'calf-raise'),
  ('single-leg-calf-raise', 'Elevación de gemelos a una pierna', 'Single-Leg Calf Raise', 'Peso corporal', 'Gemelos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'single-leg-calf-raise'),
  ('standing-calf-raise', 'Elevación de gemelos de pie', 'Standing Calf Raise', 'Máquina', 'Gemelos', '{}'::text[], 'weight_reps', false, 'fuerza', 'standing-calf-raise'),
  ('seated-calf-raise', 'Elevación de gemelos sentado', 'Seated Calf Raise', 'Máquina', 'Gemelos', '{}'::text[], 'weight_reps', false, 'fuerza', 'seated-calf-raise'),
  ('donkey-calf-raise', 'Elevación de gemelos tipo burro', 'Donkey Calf Raise', 'Máquina', 'Gemelos', '{}'::text[], 'weight_reps', false, 'fuerza', 'donkey-calf-raise'),
  ('side-lying-leg-raise', 'Elevación de pierna tumbado de lado', 'Side-Lying Leg Raise', 'Peso corporal', 'Glúteos', array['Core']::text[], 'bodyweight_reps', false, 'fuerza', 'side-lying-leg-raise'),
  ('hanging-leg-raise', 'Elevación de piernas colgado', 'Hanging Leg Raise', 'Peso corporal', 'Core', array['Grip']::text[], 'bodyweight_reps', false, 'core', 'hanging-leg-raise'),
  ('lying-leg-raise', 'Elevación de piernas tumbado', 'Lying Leg Raise', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'lying-leg-raise'),
  ('hanging-knee-raise', 'Elevación de rodillas colgado', 'Hanging Knee Raise', 'Barra de dominadas', 'Core', array['Grip']::text[], 'bodyweight_reps', false, 'core', 'hanging-knee-raise'),
  ('captains-chair-knee-raise', 'Elevación de rodillas en silla romana', 'Captain''s Chair Knee Raise', 'Máquina', 'Core', array['Hombros']::text[], 'bodyweight_reps', false, 'core', 'captains-chair-knee-raise'),
  ('prone-t-raise', 'Elevación en T boca abajo', 'Prone T Raise', 'Peso corporal', 'Espalda alta', array['Deltoides posterior', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'prone-t-raise'),
  ('prone-y-raise', 'Elevación en Y boca abajo', 'Prone Y Raise', 'Peso corporal', 'Espalda alta', array['Deltoides posterior', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'prone-y-raise'),
  ('front-raise', 'Elevaciones frontales', 'Front Raise', 'Mancuernas', 'Hombros', array['Pecho']::text[], 'weight_reps', false, 'fuerza', 'front-raise'),
  ('plate-front-raise', 'Elevaciones frontales con disco', 'Plate Front Raise', 'Disco', 'Hombros', array['Pecho']::text[], 'weight_reps', false, 'fuerza', 'plate-front-raise'),
  ('cable-front-raise', 'Elevaciones frontales en polea', 'Cable Front Raise', 'Polea', 'Hombros', array['Pecho']::text[], 'weight_reps', false, 'fuerza', 'cable-front-raise'),
  ('lateral-raise', 'Elevaciones laterales', 'Lateral Raise', 'Mancuernas', 'Hombros', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'lateral-raise'),
  ('machine-lateral-raise', 'Elevaciones laterales en máquina', 'Machine Lateral Raise', 'Máquina', 'Hombros', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'machine-lateral-raise'),
  ('cable-lateral-raise', 'Elevaciones laterales en polea', 'Cable Lateral Raise', 'Polea', 'Hombros', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'cable-lateral-raise'),
  ('elliptical', 'Elíptica', 'Elliptical', 'Cardio', 'Piernas', array['Cardio']::text[], 'duration', false, 'cardio', 'elliptical'),
  ('dumbbell-shrug', 'Encogimientos con mancuernas', 'Dumbbell Shrug', 'Mancuernas', 'Espalda alta', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-shrug'),
  ('shrug', 'Encogimientos de hombros', 'Barbell Shrug', 'Barra', 'Espalda alta', array['Antebrazos']::text[], 'weight_reps', false, 'fuerza', 'shrug'),
  ('seated-knee-tuck', 'Encogimientos sentado', 'Seated Knee Tuck', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'seated-knee-tuck'),
  ('mountain-climber', 'Escalador (mountain climber)', 'Mountain Climber', 'Peso corporal', 'Core', array['Hombros', 'Piernas']::text[], 'duration', false, 'core', 'mountain-climber'),
  ('stair-climber', 'Escaladora', 'Stair Climber', 'Cardio', 'Piernas', array['Cardio']::text[], 'duration', false, 'cardio', 'stair-climber'),
  ('standing-quad-stretch', 'Estiramiento de cuádriceps de pie', 'Standing Quad Stretch', 'Peso corporal', 'Cuádriceps', array['Cadera', 'Movilidad']::text[], 'duration', true, 'movilidad', 'standing-quad-stretch'),
  ('wall-calf-stretch', 'Estiramiento de gemelo en pared', 'Wall Calf Stretch', 'Peso corporal', 'Gemelos', array['Movilidad']::text[], 'duration', true, 'movilidad', 'wall-calf-stretch'),
  ('cross-body-shoulder-stretch', 'Estiramiento de hombro cruzado', 'Cross-Body Shoulder Stretch', 'Peso corporal', 'Hombros', array['Espalda alta', 'Movilidad']::text[], 'duration', true, 'movilidad', 'cross-body-shoulder-stretch'),
  ('hamstring-stretch', 'Estiramiento de isquiotibiales', 'Hamstring Stretch', 'Peso corporal', 'Isquiotibiales', array['Gemelos', 'Movilidad']::text[], 'duration', true, 'movilidad', 'hamstring-stretch'),
  ('doorway-chest-stretch', 'Estiramiento de pecho en puerta', 'Doorway Chest Stretch', 'Marco de puerta', 'Pecho', array['Hombros', 'Movilidad']::text[], 'duration', true, 'movilidad', 'doorway-chest-stretch'),
  ('kneeling-hip-flexor-stretch', 'Estiramiento de psoas de rodillas', 'Kneeling Hip Flexor Stretch', 'Peso corporal', 'Cadera', array['Cuádriceps', 'Movilidad']::text[], 'duration', true, 'movilidad', 'kneeling-hip-flexor-stretch'),
  ('butterfly-stretch', 'Estiramiento mariposa', 'Butterfly Stretch', 'Peso corporal', 'Cadera', array['Groin', 'Movilidad']::text[], 'duration', true, 'movilidad', 'butterfly-stretch'),
  ('leg-extension', 'Extensión de cuádriceps', 'Leg Extension', 'Máquina', 'Cuádriceps', '{}'::text[], 'weight_reps', false, 'fuerza', 'leg-extension'),
  ('wrist-extension', 'Extensión de muñeca', 'Wrist Extension', 'Mancuernas', 'Antebrazos', '{}'::text[], 'weight_reps', false, 'fuerza', 'wrist-extension'),
  ('single-arm-dumbbell-tricep-extension', 'Extensión de tríceps a una mano', 'Single Arm Dumbbell Tricep Extension', 'Mancuernas', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'single-arm-dumbbell-tricep-extension'),
  ('rope-tricep-pushdown', 'Extensión de tríceps con cuerda', 'Rope Tricep Pushdown', 'Polea', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'rope-tricep-pushdown'),
  ('dumbbell-overhead-tricep-extension', 'Extensión de tríceps con mancuerna sobre la cabeza', 'Dumbbell Overhead Tricep Extension', 'Mancuernas', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-overhead-tricep-extension'),
  ('tricep-pushdown', 'Extensión de tríceps en polea', 'Tricep Pushdown', 'Polea', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'tricep-pushdown'),
  ('overhead-tricep-extension', 'Extensión de tríceps sobre la cabeza', 'Overhead Tricep Extension', 'Polea', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'overhead-tricep-extension'),
  ('glute-focused-back-extension', 'Extensión lumbar enfocada en glúteo', 'Glute-Focused Back Extension', 'Peso corporal', 'Glúteos', array['Isquiotibiales', 'Zona lumbar']::text[], 'bodyweight_reps', false, 'fuerza', 'glute-focused-back-extension'),
  ('back-extension', 'Extensiones lumbares', 'Back Extension', 'Peso corporal', 'Zona lumbar', array['Glúteos', 'Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'back-extension'),
  ('face-pull', 'Face pull', 'Face Pull', 'Polea', 'Espalda alta', array['Deltoides posterior', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'face-pull'),
  ('banded-face-pull', 'Face pull con banda', 'Banded Face Pull', 'Banda elástica', 'Espalda alta', array['Deltoides posterior', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-face-pull'),
  ('seated-forward-fold-stretch', 'Flexión adelante sentado', 'Seated Forward Fold', 'Peso corporal', 'Isquiotibiales', array['Espalda', 'Gemelos', 'Movilidad']::text[], 'duration', true, 'movilidad', 'seated-forward-fold-stretch'),
  ('push-up', 'Flexiones', 'Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'push-up'),
  ('wide-push-up', 'Flexiones agarre ancho', 'Wide Push-up', 'Peso corporal', 'Pecho', array['Hombros', 'Tríceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'wide-push-up'),
  ('archer-push-up', 'Flexiones arquero', 'Archer Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'archer-push-up'),
  ('weighted-push-up', 'Flexiones con lastre', 'Weighted Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Core']::text[], 'weight_reps', false, 'fuerza', 'weighted-push-up'),
  ('push-up-shoulder-tap', 'Flexiones con toque de hombro', 'Push-up Shoulder Tap', 'Peso corporal', 'Core', array['Pecho', 'Hombros', 'Tríceps']::text[], 'bodyweight_reps', false, 'core', 'push-up-shoulder-tap'),
  ('handstand-push-up', 'Flexiones de pino', 'Handstand Push-up', 'Peso corporal', 'Hombros', array['Tríceps', 'Core', 'Pecho']::text[], 'bodyweight_reps', false, 'fuerza', 'handstand-push-up'),
  ('wall-handstand-push-up', 'Flexiones de pino en pared', 'Wall Handstand Push-up', 'Pared', 'Hombros', array['Tríceps', 'Core', 'Pecho']::text[], 'bodyweight_reps', false, 'fuerza', 'wall-handstand-push-up'),
  ('knee-push-up', 'Flexiones de rodillas', 'Knee Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'knee-push-up'),
  ('decline-push-up', 'Flexiones declinadas (pies elevados)', 'Decline Push-up', 'Peso corporal', 'Pecho', array['Hombros', 'Tríceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'decline-push-up'),
  ('diamond-push-up', 'Flexiones diamante', 'Diamond Push-up', 'Peso corporal', 'Tríceps', array['Pecho', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'diamond-push-up'),
  ('wall-push-up', 'Flexiones en pared', 'Wall Push-up', 'Pared', 'Pecho', array['Tríceps', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'wall-push-up'),
  ('scapular-push-up', 'Flexiones escapulares', 'Scapular Push-up', 'Peso corporal', 'Espalda alta', array['Pecho', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'scapular-push-up'),
  ('explosive-push-up', 'Flexiones explosivas', 'Explosive Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'explosive-push-up'),
  ('hindu-push-up', 'Flexiones hindúes', 'Hindu Push-up', 'Peso corporal', 'Pecho', array['Hombros', 'Tríceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'hindu-push-up'),
  ('incline-push-up', 'Flexiones inclinadas (manos elevadas)', 'Incline Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'incline-push-up'),
  ('typewriter-push-up', 'Flexiones máquina de escribir', 'Typewriter Push-up', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'typewriter-push-up'),
  ('pike-push-up', 'Flexiones pike', 'Pike Push-up', 'Peso corporal', 'Hombros', array['Tríceps', 'Pecho', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'pike-push-up'),
  ('feet-elevated-pike-push-up', 'Flexiones pike con pies elevados', 'Feet-Elevated Pike Push-up', 'Peso corporal', 'Hombros', array['Tríceps', 'Pecho', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'feet-elevated-pike-push-up'),
  ('assisted-dip', 'Fondos asistidos', 'Assisted Dip', 'Máquina', 'Tríceps', array['Pecho']::text[], 'assisted_bodyweight', false, 'fuerza', 'assisted-dip'),
  ('chest-dip', 'Fondos con énfasis en pecho', 'Chest Dip', 'Peso corporal', 'Pecho', array['Tríceps', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'chest-dip'),
  ('weighted-dip', 'Fondos con lastre', 'Weighted Dip', 'Peso corporal', 'Tríceps', array['Pecho', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'weighted-dip'),
  ('bench-dip', 'Fondos en banco', 'Bench Dip', 'Peso corporal', 'Tríceps', array['Pecho', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'bench-dip'),
  ('dip', 'Fondos en paralelas', 'Dip', 'Peso corporal', 'Tríceps', array['Pecho', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'dip'),
  ('chair-dip', 'Fondos en silla', 'Chair Dip', 'Silla', 'Tríceps', array['Pecho', 'Hombros']::text[], 'bodyweight_reps', false, 'fuerza', 'chair-dip'),
  ('frog-pump', 'Frog pump', 'Frog Pump', 'Peso corporal', 'Glúteos', array['Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'frog-pump'),
  ('banded-frog-pump', 'Frog pump con banda', 'Banded Frog Pump', 'Banda elástica', 'Glúteos', array['Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-frog-pump'),
  ('cat-cow-stretch', 'Gato-camello', 'Cat-Cow Stretch', 'Peso corporal', 'Movilidad', array['Espalda', 'Core']::text[], 'duration', true, 'movilidad', 'cat-cow-stretch'),
  ('leg-press-calf-raise', 'Gemelos en prensa', 'Leg Press Calf Raise', 'Máquina', 'Gemelos', '{}'::text[], 'weight_reps', false, 'fuerza', 'leg-press-calf-raise'),
  ('russian-twist', 'Giro ruso', 'Russian Twist', 'Peso corporal', 'Core', array['Hombros']::text[], 'bodyweight_reps', false, 'core', 'russian-twist'),
  ('weighted-russian-twist', 'Giro ruso con peso', 'Weighted Russian Twist', 'Mancuernas', 'Core', array['Hombros']::text[], 'weight_reps', false, 'core', 'weighted-russian-twist'),
  ('inchworm', 'Gusano (inchworm)', 'Inchworm', 'Peso corporal', 'Core', array['Hombros', 'Isquiotibiales', 'Pecho']::text[], 'bodyweight_reps', false, 'core', 'inchworm'),
  ('hip-airplane', 'Hip airplane', 'Hip Airplane', 'Peso corporal', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'hip-airplane'),
  ('hip-thrust', 'Hip thrust', 'Hip Thrust', 'Barra', 'Glúteos', array['Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'hip-thrust'),
  ('banded-hip-thrust', 'Hip thrust con banda', 'Banded Hip Thrust', 'Banda elástica', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-hip-thrust'),
  ('dumbbell-hip-thrust', 'Hip thrust con mancuerna', 'Dumbbell Hip Thrust', 'Mancuernas', 'Glúteos', array['Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-hip-thrust'),
  ('smith-machine-hip-thrust', 'Hip thrust en multipower', 'Smith Machine Hip Thrust', 'Máquina', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-hip-thrust'),
  ('reverse-hyperextension', 'Hiperextensión inversa', 'Reverse Hyperextension', 'Máquina', 'Glúteos', array['Isquiotibiales', 'Zona lumbar']::text[], 'bodyweight_reps', false, 'fuerza', 'reverse-hyperextension'),
  ('hollow-body-hold', 'Hollow hold', 'Hollow Body Hold', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'duration', false, 'core', 'hollow-body-hold'),
  ('hollow-rock', 'Hollow rock', 'Hollow Rock', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'hollow-rock'),
  ('dumbbell-side-bend', 'Inclinación lateral con mancuerna', 'Dumbbell Side Bend', 'Mancuernas', 'Core', array['Grip']::text[], 'weight_reps', false, 'core', 'dumbbell-side-bend'),
  ('cable-pallof-hold', 'Isometría Pallof en polea', 'Cable Pallof Hold', 'Polea', 'Core', array['Glúteos', 'Hombros']::text[], 'duration', false, 'core', 'cable-pallof-hold'),
  ('wide-grip-lat-pulldown', 'Jalón agarre ancho', 'Wide-Grip Lat Pulldown', 'Polea', 'Dorsales', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'wide-grip-lat-pulldown'),
  ('close-grip-lat-pulldown', 'Jalón agarre cerrado', 'Close-Grip Lat Pulldown', 'Polea', 'Dorsales', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'close-grip-lat-pulldown'),
  ('lat-pulldown', 'Jalón al pecho', 'Lat Pulldown', 'Polea', 'Dorsales', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'lat-pulldown'),
  ('banded-lat-pulldown', 'Jalón al pecho con banda', 'Banded Lat Pulldown', 'Banda elástica', 'Dorsales', array['Bíceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-lat-pulldown'),
  ('straight-arm-pulldown', 'Jalón con brazos extendidos', 'Straight-Arm Pulldown', 'Polea', 'Dorsales', array['Core']::text[], 'weight_reps', false, 'fuerza', 'straight-arm-pulldown'),
  ('l-sit-hold', 'L-sit', 'L-Sit Hold', 'Peso corporal', 'Core', array['Tríceps', 'Cuádriceps', 'Hombros']::text[], 'duration', false, 'core', 'l-sit-hold'),
  ('banded-woodchop', 'Leñador con banda', 'Banded Woodchop', 'Banda elástica', 'Core', array['Hombros', 'Glúteos']::text[], 'bodyweight_reps', false, 'core', 'banded-woodchop'),
  ('cable-woodchop', 'Leñador en polea', 'Cable Woodchop', 'Polea', 'Core', array['Hombros']::text[], 'weight_reps', false, 'core', 'cable-woodchop'),
  ('crab-walk', 'Marcha del cangrejo', 'Crab Walk', 'Peso corporal', 'Tríceps', array['Glúteos', 'Core', 'Hombros']::text[], 'duration', false, 'fuerza', 'crab-walk'),
  ('bear-crawl', 'Marcha del oso', 'Bear Crawl', 'Peso corporal', 'Core', array['Hombros', 'Cuádriceps', 'Cardio']::text[], 'duration', false, 'core', 'bear-crawl'),
  ('half-burpee', 'Medio burpee', 'Half Burpee', 'Peso corporal', 'Core', array['Piernas', 'Hombros', 'Cardio']::text[], 'bodyweight_reps', false, 'core', 'half-burpee'),
  ('banded-monster-walk', 'Monster walk con banda', 'Banded Monster Walk', 'Banda elástica', 'Glúteos', array['Cuádriceps', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-monster-walk'),
  ('swimming', 'Natación', 'Swimming', 'Cardio', 'Espalda', array['Hombros', 'Cardio']::text[], 'distance_duration', false, 'cardio', 'swimming'),
  ('bent-over-rear-delt-raise', 'Pájaros inclinado con mancuernas', 'Bent-Over Rear Delt Raise', 'Mancuernas', 'Deltoides posterior', array['Espalda alta']::text[], 'weight_reps', false, 'fuerza', 'bent-over-rear-delt-raise'),
  ('farmer-carry', 'Paseo del granjero', 'Farmer Carry', 'Mancuernas', 'Antebrazos', array['Espalda alta', 'Core']::text[], 'distance_duration', false, 'fuerza', 'farmer-carry'),
  ('banded-kickback', 'Patada atrás con banda', 'Banded Kickback', 'Banda elástica', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-kickback'),
  ('donkey-kick', 'Patada de glúteo', 'Donkey Kick', 'Peso corporal', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'donkey-kick'),
  ('banded-donkey-kick', 'Patada de glúteo con banda', 'Banded Donkey Kick', 'Banda elástica', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-donkey-kick'),
  ('machine-glute-kickback', 'Patada de glúteo en máquina', 'Machine Glute Kickback', 'Máquina', 'Glúteos', array['Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'machine-glute-kickback'),
  ('cable-kickback', 'Patada de glúteo en polea', 'Cable Kickback', 'Polea', 'Glúteos', array['Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'cable-kickback'),
  ('tricep-kickback', 'Patada de tríceps', 'Tricep Kickback', 'Mancuernas', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'tricep-kickback'),
  ('deadlift', 'Peso muerto', 'Deadlift', 'Barra', 'Cadena posterior', array['Espalda', 'Grip']::text[], 'weight_reps', false, 'fuerza', 'deadlift'),
  ('trap-bar-deadlift', 'Peso muerto con barra hexagonal', 'Trap Bar Deadlift', 'Barra', 'Cadena posterior', array['Cuádriceps', 'Grip']::text[], 'weight_reps', false, 'fuerza', 'trap-bar-deadlift'),
  ('romanian-deadlift', 'Peso muerto rumano', 'Romanian Deadlift', 'Barra', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'romanian-deadlift'),
  ('single-leg-romanian-deadlift', 'Peso muerto rumano a una pierna', 'Single-Leg Romanian Deadlift', 'Mancuernas', 'Isquiotibiales', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'single-leg-romanian-deadlift'),
  ('kettlebell-romanian-deadlift', 'Peso muerto rumano con kettlebell', 'Kettlebell Romanian Deadlift', 'Kettlebell', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'kettlebell-romanian-deadlift'),
  ('landmine-romanian-deadlift', 'Peso muerto rumano con landmine', 'Landmine Romanian Deadlift', 'Barra', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'landmine-romanian-deadlift'),
  ('dumbbell-romanian-deadlift', 'Peso muerto rumano con mancuernas', 'Dumbbell Romanian Deadlift', 'Mancuernas', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-romanian-deadlift'),
  ('smith-machine-romanian-deadlift', 'Peso muerto rumano en multipower', 'Smith Machine Romanian Deadlift', 'Máquina', 'Isquiotibiales', array['Glúteos', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-romanian-deadlift'),
  ('sumo-deadlift', 'Peso muerto sumo', 'Sumo Deadlift', 'Barra', 'Cadena posterior', array['Glúteos', 'Cuádriceps']::text[], 'weight_reps', false, 'fuerza', 'sumo-deadlift'),
  ('dumbbell-sumo-deadlift', 'Peso muerto sumo con mancuerna', 'Dumbbell Sumo Deadlift', 'Mancuernas', 'Cadena posterior', array['Glúteos', 'Cuádriceps', 'Aductores']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-sumo-deadlift'),
  ('fast-feet', 'Pies rápidos', 'Fast Feet', 'Peso corporal', 'Gemelos', array['Piernas', 'Cardio']::text[], 'duration', false, 'fuerza', 'fast-feet'),
  ('plank', 'Plancha', 'Plank', 'Peso corporal', 'Core', array['Hombros']::text[], 'duration', false, 'core', 'plank'),
  ('plank-jack', 'Plancha con salto de piernas', 'Plank Jack', 'Peso corporal', 'Core', array['Hombros', 'Cardio']::text[], 'duration', false, 'core', 'plank-jack'),
  ('plank-shoulder-tap', 'Plancha con toque de hombro', 'Plank Shoulder Tap', 'Peso corporal', 'Core', array['Hombros', 'Pecho']::text[], 'bodyweight_reps', false, 'core', 'plank-shoulder-tap'),
  ('copenhagen-plank', 'Plancha de Copenhague', 'Copenhagen Plank', 'Peso corporal', 'Core', array['Cuádriceps', 'Glúteos']::text[], 'duration', false, 'core', 'copenhagen-plank'),
  ('bear-plank', 'Plancha del oso', 'Bear Plank', 'Peso corporal', 'Core', array['Cuádriceps', 'Hombros']::text[], 'duration', false, 'core', 'bear-plank'),
  ('side-plank', 'Plancha lateral', 'Side Plank', 'Peso corporal', 'Core', array['Hombros']::text[], 'duration', false, 'core', 'side-plank'),
  ('side-plank-hip-dip', 'Plancha lateral con caída de cadera', 'Side Plank Hip Dip', 'Peso corporal', 'Core', array['Hombros', 'Glúteos']::text[], 'bodyweight_reps', false, 'core', 'side-plank-hip-dip'),
  ('childs-pose', 'Postura del niño', 'Child''s Pose', 'Peso corporal', 'Espalda', array['Hombros', 'Cadera', 'Movilidad']::text[], 'duration', true, 'movilidad', 'childs-pose'),
  ('leg-press', 'Prensa de piernas', 'Leg Press', 'Máquina', 'Cuádriceps', array['Glúteos', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'leg-press'),
  ('arnold-press', 'Press Arnold', 'Arnold Press', 'Mancuernas', 'Hombros', array['Tríceps']::text[], 'weight_reps', false, 'fuerza', 'arnold-press'),
  ('landmine-press', 'Press con landmine', 'Landmine Press', 'Barra', 'Hombros', array['Pecho', 'Tríceps']::text[], 'weight_reps', false, 'fuerza', 'landmine-press'),
  ('bench-press', 'Press de banca', 'Bench Press', 'Barra', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'bench-press'),
  ('close-grip-bench-press', 'Press de banca agarre cerrado', 'Close-Grip Bench Press', 'Barra', 'Tríceps', array['Pecho', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'close-grip-bench-press'),
  ('dumbbell-bench-press', 'Press de banca con mancuernas', 'Dumbbell Bench Press', 'Mancuernas', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-bench-press'),
  ('smith-machine-bench-press', 'Press de banca en multipower', 'Smith Machine Bench Press', 'Máquina', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-bench-press'),
  ('standing-dumbbell-press', 'Press de hombros de pie con mancuernas', 'Standing Dumbbell Press', 'Mancuernas', 'Hombros', array['Tríceps', 'Core']::text[], 'weight_reps', false, 'fuerza', 'standing-dumbbell-press'),
  ('machine-shoulder-press', 'Press de hombros en máquina', 'Machine Shoulder Press', 'Máquina', 'Hombros', array['Tríceps']::text[], 'weight_reps', false, 'fuerza', 'machine-shoulder-press'),
  ('seated-dumbbell-press', 'Press de hombros sentado con mancuernas', 'Dumbbell Seated Shoulder Press', 'Mancuernas', 'Hombros', array['Tríceps']::text[], 'weight_reps', false, 'fuerza', 'seated-dumbbell-press'),
  ('machine-chest-press', 'Press de pecho en máquina', 'Machine Chest Press', 'Máquina', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'machine-chest-press'),
  ('decline-bench-press', 'Press declinado con barra', 'Decline Bench Press', 'Barra', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'decline-bench-press'),
  ('decline-dumbbell-press', 'Press declinado con mancuernas', 'Decline Dumbbell Press', 'Mancuernas', 'Pecho', array['Tríceps', 'Hombros']::text[], 'weight_reps', false, 'fuerza', 'decline-dumbbell-press'),
  ('skull-crusher', 'Press francés', 'Skull Crusher', 'Barra', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'skull-crusher'),
  ('dumbbell-skull-crusher', 'Press francés con mancuernas', 'Two Dumbbell Skullcrusher', 'Mancuernas', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-skull-crusher'),
  ('single-dumbbell-skullcrusher', 'Press francés con una mancuerna', 'Single Dumbbell Skullcrusher', 'Mancuernas', 'Tríceps', array['Hombros']::text[], 'weight_reps', false, 'fuerza', 'single-dumbbell-skullcrusher'),
  ('incline-bench-press', 'Press inclinado con barra', 'Incline Bench Press', 'Barra', 'Pecho', array['Hombros', 'Tríceps']::text[], 'weight_reps', false, 'fuerza', 'incline-bench-press'),
  ('incline-dumbbell-press', 'Press inclinado con mancuernas', 'Incline Dumbbell Press', 'Mancuernas', 'Pecho', array['Hombros', 'Tríceps']::text[], 'weight_reps', false, 'fuerza', 'incline-dumbbell-press'),
  ('overhead-press', 'Press militar con barra', 'Overhead Press', 'Barra', 'Hombros', array['Tríceps']::text[], 'weight_reps', false, 'fuerza', 'overhead-press'),
  ('pallof-press', 'Press Pallof', 'Pallof Press', 'Polea', 'Core', array['Hombros']::text[], 'weight_reps', false, 'core', 'pallof-press'),
  ('banded-pallof-press', 'Press Pallof con banda', 'Banded Pallof Press', 'Banda elástica', 'Core', array['Glúteos', 'Hombros']::text[], 'bodyweight_reps', false, 'core', 'banded-pallof-press'),
  ('half-kneeling-pallof-press', 'Press Pallof de rodillas', 'Half-Kneeling Pallof Press', 'Polea', 'Core', array['Glúteos', 'Hombros']::text[], 'weight_reps', false, 'core', 'half-kneeling-pallof-press'),
  ('glute-bridge', 'Puente de glúteos', 'Glute Bridge', 'Peso corporal', 'Glúteos', array['Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'glute-bridge'),
  ('single-leg-glute-bridge', 'Puente de glúteos a una pierna', 'Single-Leg Glute Bridge', 'Peso corporal', 'Glúteos', array['Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'single-leg-glute-bridge'),
  ('banded-glute-bridge', 'Puente de glúteos con banda', 'Banded Glute Bridge', 'Banda elástica', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-glute-bridge'),
  ('barbell-glute-bridge', 'Puente de glúteos con barra', 'Barbell Glute Bridge', 'Barra', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'barbell-glute-bridge'),
  ('dumbbell-glute-bridge', 'Puente de glúteos con mancuerna', 'Dumbbell Glute Bridge', 'Mancuernas', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-glute-bridge'),
  ('glute-bridge-march', 'Puente de glúteos con marcha', 'Glute Bridge March', 'Peso corporal', 'Glúteos', array['Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'glute-bridge-march'),
  ('cable-pull-through', 'Pull through en polea', 'Cable Pull-Through', 'Polea', 'Glúteos', array['Isquiotibiales', 'Zona lumbar']::text[], 'weight_reps', false, 'fuerza', 'cable-pull-through'),
  ('push-press', 'Push press', 'Push Press', 'Barra', 'Hombros', array['Tríceps', 'Cuádriceps']::text[], 'weight_reps', false, 'fuerza', 'push-press'),
  ('rack-pull', 'Rack pull', 'Rack Pull', 'Barra', 'Espalda', array['Glúteos', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'rack-pull'),
  ('one-arm-dumbbell-row', 'Remo a una mano con mancuerna', 'One-Arm Dumbbell Row', 'Mancuernas', 'Espalda', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'one-arm-dumbbell-row'),
  ('single-arm-cable-row', 'Remo a una mano en polea', 'Single-Arm Cable Row', 'Polea', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'single-arm-cable-row'),
  ('upright-row', 'Remo al mentón', 'Upright Row', 'Barra', 'Hombros', array['Espalda alta', 'Bíceps']::text[], 'weight_reps', false, 'fuerza', 'upright-row'),
  ('banded-row', 'Remo con banda', 'Banded Row', 'Banda elástica', 'Espalda', array['Bíceps', 'Espalda alta']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-row'),
  ('barbell-row', 'Remo con barra', 'Barbell Row', 'Barra', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'barbell-row'),
  ('chest-supported-row', 'Remo con pecho apoyado', 'Chest Supported Row', 'Máquina', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'chest-supported-row'),
  ('towel-row', 'Remo con toalla', 'Towel Row', 'Toalla', 'Espalda', array['Bíceps', 'Espalda alta', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'towel-row'),
  ('machine-row', 'Remo en máquina', 'Machine Row', 'Máquina', 'Espalda', array['Bíceps']::text[], 'weight_reps', false, 'fuerza', 'machine-row'),
  ('doorway-row', 'Remo en marco de puerta', 'Doorway Row', 'Marco de puerta', 'Espalda', array['Bíceps', 'Espalda alta', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'doorway-row'),
  ('t-bar-row', 'Remo en T', 'T-Bar Row', 'Máquina', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 't-bar-row'),
  ('rowing', 'Remo ergómetro', 'Rowing', 'Cardio', 'Espalda', array['Piernas', 'Cardio']::text[], 'distance_duration', false, 'cardio', 'rowing'),
  ('dumbbell-bent-over-row', 'Remo inclinado con mancuernas', 'Dumbbell Bent Over Row', 'Mancuernas', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-bent-over-row'),
  ('inverted-row', 'Remo invertido', 'Inverted Row', 'Peso corporal', 'Espalda', array['Bíceps', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'inverted-row'),
  ('meadows-row', 'Remo Meadows', 'Meadows Row', 'Barra', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'meadows-row'),
  ('pendlay-row', 'Remo Pendlay', 'Pendlay Row', 'Barra', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'pendlay-row'),
  ('seated-row', 'Remo sentado en polea', 'Seated Cable Row', 'Polea', 'Espalda', array['Bíceps', 'Deltoides posterior']::text[], 'weight_reps', false, 'fuerza', 'seated-row'),
  ('high-knees', 'Rodillas altas', 'High Knees', 'Peso corporal', 'Piernas', array['Core', 'Cardio']::text[], 'duration', false, 'fuerza', 'high-knees'),
  ('torso-twist-stretch', 'Rotación de torso', 'Torso Twists', 'Peso corporal', 'Movilidad', array['Core', 'Espalda']::text[], 'duration', true, 'movilidad', 'torso-twist-stretch'),
  ('ab-wheel', 'Rueda abdominal', 'Ab Wheel Rollout', 'Peso corporal', 'Core', array['Hombros']::text[], 'bodyweight_reps', false, 'core', 'ab-wheel'),
  ('jump-rope', 'Saltar la cuerda', 'Jump Rope', 'Cardio', 'Gemelos', array['Cardio', 'Hombros']::text[], 'duration', false, 'cardio', 'jump-rope'),
  ('skater-hop', 'Salto del patinador', 'Skater Hop', 'Peso corporal', 'Piernas', array['Glúteos', 'Gemelos', 'Cardio']::text[], 'bodyweight_reps', false, 'fuerza', 'skater-hop'),
  ('jumping-jack', 'Saltos de tijera', 'Jumping Jack', 'Peso corporal', 'Piernas', array['Hombros', 'Gemelos', 'Cardio']::text[], 'duration', false, 'fuerza', 'jumping-jack'),
  ('seal-jack', 'Seal jack', 'Seal Jack', 'Peso corporal', 'Pecho', array['Hombros', 'Piernas', 'Cardio']::text[], 'duration', false, 'fuerza', 'seal-jack'),
  ('hiking', 'Senderismo', 'Hiking', 'Cardio', 'Piernas', array['Glúteos', 'Cardio']::text[], 'distance_duration', false, 'cardio', 'hiking'),
  ('single-leg-box-squat', 'Sentadilla a una pierna en cajón', 'Single-Leg Box Squat', 'Cajón', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'single-leg-box-squat'),
  ('bulgarian-split-squat', 'Sentadilla búlgara', 'Bulgarian Split Squat', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'bulgarian-split-squat'),
  ('smith-machine-bulgarian-split-squat', 'Sentadilla búlgara en multipower', 'Smith Machine Bulgarian Split Squat', 'Máquina', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-bulgarian-split-squat'),
  ('banded-squat', 'Sentadilla con banda', 'Banded Squat', 'Banda elástica', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'banded-squat'),
  ('squat', 'Sentadilla con barra', 'Squat', 'Barra', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'squat'),
  ('belt-squat', 'Sentadilla con cinturón', 'Belt Squat', 'Máquina', 'Cuádriceps', array['Glúteos']::text[], 'weight_reps', false, 'fuerza', 'belt-squat'),
  ('landmine-squat', 'Sentadilla con landmine', 'Landmine Squat', 'Barra', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'landmine-squat'),
  ('jump-squat', 'Sentadilla con salto', 'Jump Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Gemelos']::text[], 'bodyweight_reps', false, 'fuerza', 'jump-squat'),
  ('cossack-squat', 'Sentadilla cosaca', 'Cossack Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'cossack-squat'),
  ('skater-squat', 'Sentadilla del patinador', 'Skater Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'skater-squat'),
  ('smith-machine-squat', 'Sentadilla en multipower', 'Smith Machine Squat', 'Máquina', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-squat'),
  ('front-squat', 'Sentadilla frontal', 'Front Squat', 'Barra', 'Cuádriceps', array['Core', 'Glúteos']::text[], 'weight_reps', false, 'fuerza', 'front-squat'),
  ('goblet-squat', 'Sentadilla goblet', 'Goblet Squat', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'goblet-squat'),
  ('heel-elevated-goblet-squat', 'Sentadilla goblet con talones elevados', 'Heel-Elevated Goblet Squat', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'heel-elevated-goblet-squat'),
  ('hack-squat', 'Sentadilla hack', 'Hack Squat', 'Máquina', 'Cuádriceps', array['Glúteos']::text[], 'weight_reps', false, 'fuerza', 'hack-squat'),
  ('wall-sit', 'Sentadilla isométrica en pared', 'Wall Sit', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'duration', false, 'fuerza', 'wall-sit'),
  ('pistol-squat', 'Sentadilla pistol', 'Pistol Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'pistol-squat'),
  ('assisted-pistol-squat', 'Sentadilla pistol asistida', 'Assisted Pistol Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'assisted-pistol-squat'),
  ('shrimp-squat', 'Sentadilla shrimp', 'Shrimp Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'shrimp-squat'),
  ('bodyweight-squat', 'Sentadilla sin peso', 'Bodyweight Squat', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'bodyweight-squat'),
  ('sissy-squat', 'Sentadilla sissy', 'Sissy Squat', 'Peso corporal', 'Cuádriceps', array['Core', 'Gemelos']::text[], 'bodyweight_reps', false, 'fuerza', 'sissy-squat'),
  ('dumbbell-sumo-squat', 'Sentadilla sumo con mancuerna', 'Dumbbell Sumo Squat', 'Mancuernas', 'Glúteos', array['Cuádriceps', 'Aductores', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-sumo-squat'),
  ('skierg', 'SkiErg', 'SkiErg', 'Cardio', 'Espalda', array['Tríceps', 'Core', 'Cardio']::text[], 'distance_duration', false, 'cardio', 'skierg'),
  ('sprawl', 'Sprawl', 'Sprawl', 'Peso corporal', 'Piernas', array['Core', 'Hombros', 'Cardio']::text[], 'bodyweight_reps', false, 'fuerza', 'sprawl'),
  ('squat-thrust', 'Squat thrust', 'Squat Thrust', 'Peso corporal', 'Core', array['Piernas', 'Hombros', 'Cardio']::text[], 'bodyweight_reps', false, 'core', 'squat-thrust'),
  ('step-up', 'Subida al cajón', 'Step-Up', 'Mancuernas', 'Cuádriceps', array['Glúteos']::text[], 'weight_reps', false, 'fuerza', 'step-up'),
  ('superman', 'Superman', 'Superman', 'Peso corporal', 'Zona lumbar', array['Glúteos', 'Espalda alta', 'Isquiotibiales']::text[], 'bodyweight_reps', false, 'fuerza', 'superman'),
  ('superman-hold', 'Superman isométrico', 'Superman Hold', 'Peso corporal', 'Zona lumbar', array['Glúteos', 'Espalda alta', 'Isquiotibiales']::text[], 'duration', false, 'fuerza', 'superman-hold'),
  ('kettlebell-swing', 'Swing con kettlebell', 'Kettlebell Swing', 'Kettlebell', 'Glúteos', array['Isquiotibiales', 'Core', 'Cardio']::text[], 'weight_reps', false, 'fuerza', 'kettlebell-swing'),
  ('flutter-kick', 'Tijeras', 'Flutter Kick', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'duration', false, 'core', 'flutter-kick'),
  ('toe-touch', 'Toque de puntas', 'Toe Touch', 'Peso corporal', 'Core', '{}'::text[], 'bodyweight_reps', false, 'core', 'toe-touch'),
  ('heel-tap', 'Toque de talones', 'Heel Tap', 'Peso corporal', 'Core', '{}'::text[], 'bodyweight_reps', false, 'core', 'heel-tap'),
  ('v-up', 'V-up', 'V-Up', 'Peso corporal', 'Core', array['Cuádriceps']::text[], 'bodyweight_reps', false, 'core', 'v-up'),
  ('wall-walk', 'Wall walk', 'Wall Walk', 'Pared', 'Hombros', array['Core', 'Pecho', 'Tríceps']::text[], 'bodyweight_reps', false, 'fuerza', 'wall-walk'),
  ('deficit-reverse-lunge', 'Zancada atrás en déficit', 'Deficit Reverse Lunge', 'Mancuernas', 'Glúteos', array['Cuádriceps', 'Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'deficit-reverse-lunge'),
  ('smith-machine-reverse-lunge', 'Zancada atrás en multipower', 'Smith Machine Reverse Lunge', 'Máquina', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-reverse-lunge'),
  ('front-foot-elevated-split-squat', 'Zancada con pie delantero elevado', 'Front-Foot Elevated Split Squat', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'front-foot-elevated-split-squat'),
  ('curtsy-lunge', 'Zancada cruzada', 'Curtsy Lunge', 'Peso corporal', 'Glúteos', array['Cuádriceps', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'curtsy-lunge'),
  ('dumbbell-curtsy-lunge', 'Zancada cruzada con mancuerna', 'Dumbbell Curtsy Lunge', 'Mancuernas', 'Glúteos', array['Cuádriceps', 'Isquiotibiales', 'Core']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-curtsy-lunge'),
  ('split-squat', 'Zancada estática', 'Split Squat', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'split-squat'),
  ('smith-machine-split-squat', 'Zancada estática en multipower', 'Smith Machine Split Squat', 'Máquina', 'Cuádriceps', array['Glúteos', 'Core']::text[], 'weight_reps', false, 'fuerza', 'smith-machine-split-squat'),
  ('forward-lunge', 'Zancada hacia adelante', 'Forward Lunge', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'forward-lunge'),
  ('reverse-lunge', 'Zancada hacia atrás', 'Reverse Lunge', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'reverse-lunge'),
  ('lateral-lunge', 'Zancada lateral', 'Lateral Lunge', 'Peso corporal', 'Cuádriceps', array['Glúteos', 'Isquiotibiales', 'Core']::text[], 'bodyweight_reps', false, 'fuerza', 'lateral-lunge'),
  ('dumbbell-lateral-lunge', 'Zancada lateral con mancuerna', 'Dumbbell Lateral Lunge', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Aductores', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'dumbbell-lateral-lunge'),
  ('walking-lunge', 'Zancadas caminando', 'Walking Lunge', 'Mancuernas', 'Cuádriceps', array['Glúteos', 'Isquiotibiales']::text[], 'weight_reps', false, 'fuerza', 'walking-lunge')
on conflict (slug) do update set
  name             = excluded.name,
  name_en          = excluded.name_en,
  equipment        = excluded.equipment,
  primary_muscle   = excluded.primary_muscle,
  secondary_muscles= excluded.secondary_muscles,
  exercise_type    = excluded.exercise_type,
  is_stretch       = excluded.is_stretch,
  category         = excluded.category,
  animation_slug   = excluded.animation_slug;
